spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://postgres-db:5432/catalog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Change from 'update' to 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-migration-naming: true

server:
  port: 6005
  servlet:
    context-path: /catalog

logging:
  level:
    com.nexxserve.catalog: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG  # Add to see Flyway logs

grpc:
  server:
    port: 6105

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.uuid}
    metadata-map:
      grpc-port: ${grpc.server.port}

# Enable Spring Boot Actuator endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always