spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Change from 'update' to 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-migration-naming: true

server:
  port: 7080
  servlet:
    context-path: /catalog

logging:
  level:
    com.nexxserve.catalog: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG  # Add to see Flyway logs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
grpc:
  server:
    port: 7090