spring:
  task:
    scheduling:
      pool:
        size: 5
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600 # 1 hour for most static resources
  application:
    name: inventory

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
  access-token-expiration: 86400
  refresh-token-expiration: 604800

server:
  port: 5007

logging:
  level:
    com.nexxserve: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pharmacy-inventory.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

app:
  report:
    retry:
      interval: 60000
      max-retries: 5
    cleanup:
      cron: "0 0 2 * * *"
  connectivity:
    check:
      urls: https://www.google.com,https://www.cloudflare.com,https://httpbin.org/status/200
      timeout: 5000
  credentials:
    secret: "YourSecureEncryptionKeyHere123456"  # Must be the same across restarts
    salt: "5c0744940b5c369b"