spring:
  application:
    name: medadmin
  datasource:
    url: jdbc:postgresql://localhost:5432/medadmin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
jwt:
  secret: NexxServeMedAdminSecretKeyForJwtThatIsAtLeast32BytesLong

logging:
  level:
    com.nexxserve: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO