version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: medadmin_db
    environment:
      POSTGRES_DB: medadmin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medadmin_app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
