spring:
  application:
    name: medicalemr
  datasource:
    url: jdbc:postgresql://localhost:5432/medicalemr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
server:
  port: 5008

logging:
  level:
    com.nexxserve: DEBUG
    org.springframework.security: DEBUG